image:
  tag: latest

imagePullSecretsDockerconfigjsonBase64: null

env:
  API_ID: null
  API_HASH: null
  SESSION_STRING: null
  TARGET_CHANNEL: null
  OPENAI_API_KEY: null
  MODEL_NAME: null
  MONGO_DB_NAME: null
  MONGO_DB_HOST: null
  MONGO_DB_PORT: null
  MONGO_DB_USERNAME: null
  MONGO_DB_PASSWORD: null
