version: "0.41.1"

registries:
  - host: registry-1.docker.io

.options: &options
  namespace: telegram-osint-app
  create_namespace: true
  max_history: 3 # best practice

releases:
  - name: telegram-osint-app
    chart: infrastructure/helm-chart
    <<: *options

